server {
    # Nginx будет слушать порт, который мы передадим при старте
    listen ${PORT}; 

    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        # ... остальные заголовки
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}